"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { Student, Session, Tutor } from "@/lib/supabase";

type ReportData = {
  tutor: Tutor;
  student: Student;
  sessions: Session[];
  skills: Record<string, number[]>;
  totalSessions: number;
  totalRevenue: number;
  avgScore: number;
};

function generateHTML(r: ReportData): string {
  const skillRows = Object.entries(r.skills).map(([skill, scores]) => {
    const latest = scores[scores.length - 1];
    const first = scores[0];
    const delta = latest - first;
    const bars = scores.map((s) => `<span style="display:inline-block;width:18px;height:${s * 14}px;background:${s>=8?'#10b981':s>=6?'#3b82f6':s>=4?'#f59e0b':'#ef4444'};border-radius:2px;vertical-align:bottom;margin:0 1px;"></span>`).join("");
    return `<tr><td style="padding:10px 12px;font-size:14px;font-weight:600;">${skill}</td><td style="padding:10px 12px;text-align:center;">${first}/10</td><td style="padding:10px 12px;text-align:center;">${latest}/10</td><td style="padding:10px 12px;text-align:center;color:${delta>0?'#10b981':delta<0?'#ef4444':'#64748b'};">${delta>0?'+':''}${delta}</td><td style="padding:10px 12px;">${bars}</td></tr>`;
  }).join("");

  const recentSessions = r.sessions.slice(-5).reverse().map((s) => `<tr><td style="padding:8px 12px;font-size:13px;">${s.date}</td><td style="padding:8px 12px;font-size:13px;">${s.subject||"General"}</td><td style="padding:8px 12px;font-size:13px;">${s.duration_min}min</td><td style="padding:8px 12px;font-size:13px;">${s.notes||"—"}</td></tr>`).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Progress Report — ${r.student.name}</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:0;background:#f8fafc;color:#1e293b;}
.page{max-width:800px;margin:0 auto;background:white;padding:48px;box-shadow:0 0 40px rgba(0,0,0,.1);}
.header{border-bottom:3px solid #6366f1;padding-bottom:24px;margin-bottom:32px;}
.badge{display:inline-block;background:#ede9fe;color:#6366f1;font-size:11px;font-weight:700;padding:3px 10px;border-radius:99px;letter-spacing:.05em;text-transform:uppercase;}
h1{font-size:28px;font-weight:900;margin:8px 0 4px;color:#1e293b;}
.subtitle{color:#64748b;font-size:14px;}
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0;}
.stat{background:#f1f5f9;border-radius:12px;padding:16px;text-align:center;}
.stat-num{font-size:28px;font-weight:900;color:#6366f1;}
.stat-label{font-size:12px;color:#64748b;margin-top:2px;}
h2{font-size:18px;font-weight:700;color:#1e293b;margin:28px 0 12px;border-left:4px solid #6366f1;padding-left:12px;}
table{width:100%;border-collapse:collapse;}
th{background:#f8fafc;font-size:11px;font-weight:700;text-transform:uppercase;color:#64748b;padding:10px 12px;text-align:left;border-bottom:2px solid #e2e8f0;}
tr:nth-child(even){background:#f8fafc;}
.footer{margin-top:40px;padding-top:20px;border-top:1px solid #e2e8f0;text-align:center;color:#94a3b8;font-size:12px;}
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <span class="badge">Progress Report</span>
    <h1>${r.student.name}</h1>
    <div class="subtitle">Prepared by ${r.tutor.business_name || r.tutor.name} · Generated ${new Date().toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</div>
    ${r.student.parent_name ? `<div class="subtitle" style="margin-top:4px;">For ${r.student.parent_name}</div>` : ""}
  </div>

  <div class="stats">
    <div class="stat"><div class="stat-num">${r.totalSessions}</div><div class="stat-label">Sessions Completed</div></div>
    <div class="stat"><div class="stat-num">${r.avgScore > 0 ? r.avgScore.toFixed(1) : "—"}</div><div class="stat-label">Avg Skill Score (/ 10)</div></div>
    <div class="stat"><div class="stat-num">${r.student.grade_level || "—"}</div><div class="stat-label">Grade Level</div></div>
  </div>

  ${Object.keys(r.skills).length > 0 ? `
  <h2>Skill Progress</h2>
  <table>
    <thead><tr><th>Skill</th><th>Starting</th><th>Current</th><th>Change</th><th>Trend</th></tr></thead>
    <tbody>${skillRows}</tbody>
  </table>` : ""}

  ${recentSessions ? `
  <h2>Recent Sessions</h2>
  <table>
    <thead><tr><th>Date</th><th>Subject</th><th>Duration</th><th>Notes</th></tr></thead>
    <tbody>${recentSessions}</tbody>
  </table>` : ""}

  <div class="footer">
    Generated by TutorPulse · tutorpulse.io · ${r.tutor.business_name || r.tutor.name}
  </div>
</div>
</body>
</html>`;
}

export default function ReportsPage() {
  const [students, setStudents] = useState<Student[]>([]);
  const [tutor, setTutor] = useState<Tutor | null>(null);
  const [selectedStudentId, setSelectedStudentId] = useState("");
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    supabase.auth.getSession().then(async ({ data }) => {
      if (!data.session) return;
      const { data: t } = await supabase.from("tutors").select("*").eq("auth_id", data.session.user.id).single();
      if (t) {
        setTutor(t);
        const { data: studs } = await supabase.from("students").select("*").eq("tutor_id", t.id).eq("status", "active").order("name");
        setStudents(studs || []);
      }
      setLoading(false);
    });
  }, []);

  async function generateReport() {
    if (!selectedStudentId || !tutor) return;
    setGenerating(true);

    const student = students.find((s) => s.id === selectedStudentId)!;
    const { data: sessions } = await supabase
      .from("sessions")
      .select("*")
      .eq("student_id", selectedStudentId)
      .eq("status", "completed")
      .order("date", { ascending: true });

    const ss = sessions || [];
    const skills: Record<string, number[]> = {};
    ss.forEach((s: Session) => {
      Object.entries(s.skill_scores || {}).forEach(([skill, score]) => {
        if (!skills[skill]) skills[skill] = [];
        skills[skill].push(score as number);
      });
    });

    const allScores = Object.values(skills).flatMap((a) => a);
    const avgScore = allScores.length > 0 ? allScores.reduce((a, b) => a + b, 0) / allScores.length : 0;
    const totalRevenue = ss.reduce((sum: number, s: Session) => sum + (s.rate * s.duration_min) / 60, 0);

    const html = generateHTML({ tutor, student, sessions: ss, skills, totalSessions: ss.length, totalRevenue, avgScore });

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `progress-report-${student.name.toLowerCase().replace(/\s+/g, "-")}-${new Date().toISOString().split("T")[0]}.html`;
    a.click();
    URL.revokeObjectURL(url);
    setGenerating(false);
  }

  if (loading) return <div className="p-8 text-slate-400 animate-pulse">Loading...</div>;

  return (
    <div className="p-8">
      <h1 className="text-2xl font-black text-slate-900 mb-2">Parent Progress Reports</h1>
      <p className="text-slate-500 mb-8">Generate professional progress reports to share with parents.</p>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Generator */}
        <div className="bg-white border border-slate-200 rounded-xl p-6">
          <h2 className="font-bold mb-4">Generate Report</h2>
          <div className="mb-4">
            <label className="block text-sm text-slate-600 mb-2">Select Student</label>
            <select
              value={selectedStudentId}
              onChange={(e) => setSelectedStudentId(e.target.value)}
              className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-400"
            >
              <option value="">Choose a student...</option>
              {students.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </div>
          <div className="bg-indigo-50 border border-indigo-100 rounded-lg p-4 mb-4 text-sm text-indigo-700">
            <strong>Report includes:</strong>
            <ul className="mt-2 space-y-1">
              <li>✓ Skill progression charts with scores over time</li>
              <li>✓ Session history summary</li>
              <li>✓ Progress delta (improvement since start)</li>
              <li>✓ Your business branding</li>
            </ul>
          </div>
          <button
            onClick={generateReport}
            disabled={!selectedStudentId || generating}
            className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-bold py-3 rounded-xl transition-colors"
          >
            {generating ? "Generating..." : "📋 Download Report (HTML)"}
          </button>
          <p className="text-xs text-slate-400 mt-2 text-center">Opens in browser · Print to PDF for sharing</p>
        </div>

        {/* Preview */}
        <div className="bg-gradient-to-br from-indigo-50 to-purple-50 border border-indigo-100 rounded-xl p-6">
          <h2 className="font-bold mb-4 text-indigo-900">What Parents See</h2>
          <div className="bg-white rounded-lg shadow-sm p-4 text-xs space-y-3">
            <div className="border-b border-slate-100 pb-3">
              <div className="inline-block bg-indigo-100 text-indigo-600 text-xs px-2 py-0.5 rounded-full font-bold uppercase">Progress Report</div>
              <div className="font-black text-base mt-1">Emma Johnson</div>
              <div className="text-slate-400">Prepared by {tutor?.business_name || tutor?.name || "Your Business"}</div>
            </div>
            <div className="flex gap-2">
              {["12 Sessions", "7.8 Avg Score", "Grade 9"].map((s) => (
                <div key={s} className="flex-1 bg-slate-50 rounded-lg p-2 text-center">
                  <div className="font-black text-indigo-600 text-sm">{s.split(" ")[0]}</div>
                  <div className="text-slate-400 text-xs">{s.split(" ").slice(1).join(" ")}</div>
                </div>
              ))}
            </div>
            <div>
              <div className="font-bold text-slate-700 mb-1">Algebra II</div>
              <div className="flex gap-0.5 items-end">
                {[4,5,5,6,6,7,7,8,8,9].map((v, i) => (
                  <div key={i} className="w-4 rounded-t-sm" style={{ height: v * 5, background: v >= 8 ? "#10b981" : v >= 6 ? "#3b82f6" : "#f59e0b" }} />
                ))}
              </div>
              <div className="text-xs text-emerald-600 mt-1">↑ +5 points improvement</div>
            </div>
          </div>
          <p className="text-xs text-indigo-400 mt-3 text-center">Professional reports that justify your rates</p>
        </div>
      </div>
    </div>
  );
}
